name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm

      - run: npm ci

      - name: Run check:ci
        run: npm run check:ci

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm

      - run: npm ci

      - name: Run Jest
        run: npm run test:coverage

      - uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3.1.6
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./coverage/ # optional
          fail_ci_if_error: true # optional2 (default = false)

  pack:
    name: pack
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm

      - run: npm ci

      - name: Run build
        run: npm run build

      - name: Run pack
        run: npm publish --dry-run --ignore-scripts
