name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version-file: .node-version
          cache: npm

      - run: npm ci

      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: "./**/*.{ts,js}"

      - name: Run eslint
        run: npm run lint

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version-file: .node-version
          cache: npm

      - run: npm ci

      - name: Run Jest
        run: npm run test:coverage

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./coverage/ # optional
          fail_ci_if_error: true # optional2 (default = false)

  pack:
    name: pack
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version-file: .node-version
          cache: npm

      - run: npm ci

      - name: Run build
        run: npm run build

      - name: Run pack
        run: npm publish --dry-run --ignore-scripts
