name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write
      
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@ca6063f4ed81b55db15b8c42d1b6f7925866342d # v3
        id: release
        with:
          release-type: node
          package-name: zenn-metadata-updater

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version-file: .node-version
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish --provenance
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
